### ISSUE TITLE
Severe bug with Perfect Vision module

### ISSUE THREAD

**Issue by Nedrapter** [sPOiDar/fvtt-module-better-target#5] opened 2021-10-31 05:42 UTC
When having Perfect Vision and Better Target modules and trying to target a small sized token by double right clicking on it, the user's interface freezes and becomes unresponding.
The following errors pop in the console:
![image](https://user-images.githubusercontent.com/74311190/139569620-588a3ea7-bded-4f46-b9ef-ada2960506d0.png)
I know the Better Target is not mentioned in those error, but the problem only happens when those 2 modules are active and target a small token.

Dnd 5e system

**Comment by sPOiDar** [comment] 2021-10-31 09:18
I know there's an issue with certain grid sizes (#3), looks like maybe it's related. The issue is upstream with one of the PIXI dependencies (PIXI is the rendering library that Foundry uses).

Maybe something about the way Perfect Vision modifies the renderer triggers this bug more easily, but you could try adjusting the grid size and see if it still happens.

**Comment by Nedrapter** [comment] 2021-10-31 09:20
The grid however is perfectly aligned with the maps. Changing it would make everything unaligned.

**Comment by sPOiDar** [comment] 2021-10-31 09:22
Yeah, you'd have to rescale or something. There's literally nothing I can do to fix this here though, AFAICT. I'd be happy to be proved wrong, but I think that was my takeaway last time I tried to solve this.

**Comment by sPOiDar** [comment] 2021-10-31 10:09
I lied. After digging into it, I think I understand what happens at certain grid sizes - depending on width, it's possible for calculation of the hole size to end up being zero, in which case earcut explodes rather than just not doing anything.

I should be able to solve this by scaling a couple of the dimensions to ensure that a hole will always be present.

**Comment by sPOiDar** [comment] 2021-10-31 10:36
Should be fixed in v0.1.17, please let me know of any issues.

**Closed as completed by sPOiDar** 2021-10-31 10:36 UTC
Labels: bug, duplicate
